### ISSUE TITLE
Translate `The indieDev` page design

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#10]
## Tasks
- [x] #11
- [ ] Add filter functionality for `The indieDev` article list
- [x] Subtitle needs to a bit larger, for readability.
- [x] Add missing articles images
- [x] Order articles by date
- [x] Check that article dates are correct
- [x] Present dates in this format: August 25, 2023
- [x] Recheck resizing: the title is getting too small too early, the date should always be smaller, and they don't seem to be centered at some points.
