### ISSUE TITLE
Translate `BlogPost` page design

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#13]
## Tasks
- [x] Featured image must be larger to follow the design
- [x] Add date in correct format & author info. Below the featured image.
- [x] Title must be larger and with a max width that follows the design
- [x] Add categories and tags to the header (disable for now)
- [ ] Article background: `Schemes/Surface`
- [ ] Turn blog links into NextLink
- [x] Turn images into NextImage
- [ ] #14
- [x] images must be smaller on smaller devices?
- [x] #17
- [x] Grab iFrame vid link from frontMatter?
- [ ] Add related section/component
- [x] #18
- [ ] Start with a larger first letter in the article
- [x] Rounded post images
- [x] Post images a bit smaller?
- [ ] Wider article width
- [x] Code blocks must fit within the article
- [ ] Code highlights
- [ ] Copy Btn in code blocks
- [ ] Headlines Roboto?
- [ ] Revise spacing between page items
- [ ] Smaller tags on smaller width devices? Or organize them a bit more neatly
