### ISSUE TITLE
Add OneExercise page copy & gifs

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#19]
## Tasks
- [ ] Record short vids
- [ ] Write a minimal amount of clean copy in data file
- [ ] Refactor the showcase components to give the option of adding a vid/image/device(with image) as a child instead of only a device.
