### ISSUE TITLE
Finish coding landing page design

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#2]
# Tasks
- [x] Select & streamline trigger actions color
- [ ] more space between logoDisplay items
- [x] colors
- [x] dark mode
- [ ] fix sizing mess
