### ISSUE TITLE
Add 1xercise showcase

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#3]
# Tasks
- [x] add device frame
- [x] load 1Xercise in device
- [x] add link below device
- [x] add border around device
- [x] Add text left
- [x] Add text right
- [x] Responsive
