### ISSUE TITLE
Finish Coding 1Xercise landing page

### ISSUE THREAD

**Issue by mstflotfy** [mstflotfy/mstflotfy.com-2024-nextJs#5]
## Tasks
- [x] logo
- [x] #7
- [x] features section
- [x] #8
- [x] Custom colors
- [x] Consider removing margin from footer and add it manually to last section in each page. So that I can easily change the color of this margin to that of the last section of the page if needed.
- [x] Responsive (adapt to medium, small, and xl devices)
- [ ] Make and add the gifs
- [ ] Add Copy
- [ ] The features and table of content should be accessible
- [ ] Make the text next to the try here device above the fold
